import type { Metadata } from "next";
import { Card, Shell } from "@/components/shell";

export const metadata: Metadata = { title: "Terms of Use — Utabiri" };

const sections: { heading: string; body: string[] }[] = [
  {
    heading: "1. Who we are",
    body: [
      "Utabiri is a Kenyan economics platform that publishes commodity price data, macro indicators, and AI-generated commentary, forecasts and recommendations. By creating an account or using the platform you agree to these Terms.",
    ],
  },
  {
    heading: "2. Eligibility",
    body: [
      "You must be at least 18 years old and legally resident in Kenya to register an account. You may hold only one account, registered in your own name, and you are responsible for keeping your login credentials secure.",
    ],
  },
  {
    heading: "3. Nature of the content",
    body: [
      "Commodity price data is sourced from the Kenya Ministry of Agriculture's KAMIS bulletin and may contain gaps or delays. Commentary, forecasts and recommendations are generated by an AI model and are provided for informational purposes only — they are not financial, agronomic, or investment advice, and you should not rely on them as the sole basis for any decision.",
    ],
  },
  {
    heading: "4. Community features",
    body: [
      "Registered users may comment on insights, follow other users, and set personalization interests. You are responsible for the content you post — do not post anything unlawful, abusive, or that infringes others' rights. We may remove content or suspend accounts that breach these Terms.",
    ],
  },
  {
    heading: "5. Prohibited conduct",
    body: [
      "You may not: operate multiple or shared accounts, use bots or scrapers against the platform without permission, attempt to manipulate or disrupt the service, or use the platform for unlawful purposes.",
    ],
  },
  {
    heading: "6. Service availability and liability",
    body: [
      "The platform is provided on an \"as is\" basis. We work to keep it available and accurate but do not guarantee uninterrupted service or error-free data. To the maximum extent permitted by Kenyan law, we are not liable for decisions made in reliance on content shown on the platform.",
    ],
  },
  {
    heading: "7. Account closure",
    body: [
      "You may close your account at any time by contacting support. We may suspend or close accounts that breach these Terms.",
    ],
  },
  {
    heading: "8. Changes and governing law",
    body: [
      "We may update these Terms; material changes will be announced in the app and apply prospectively. These Terms are governed by the laws of Kenya and disputes are subject to the jurisdiction of Kenyan courts.",
    ],
  },
];

export default function TermsPage() {
  return (
    <Shell title="Terms of Use" subtitle="Last updated: June 2026">
      <Card className="space-y-6">
        {sections.map((s) => (
          <section key={s.heading}>
            <h2 className="text-base font-bold">{s.heading}</h2>
            {s.body.map((p, i) => (
              <p key={i} className="mt-2 text-sm leading-relaxed text-mut">
                {p}
              </p>
            ))}
          </section>
        ))}
        <p className="text-sm text-mut">
          Questions? Contact{" "}
          <a href="mailto:support@utabiri.co.ke" className="font-semibold text-accent-2 hover:underline">
            support@utabiri.co.ke
          </a>
          . See also our{" "}
          <a href="/privacy" className="font-semibold text-accent-2 hover:underline">
            Privacy Policy
          </a>
          .
        </p>
      </Card>
    </Shell>
  );
}
